/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/csrf": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["SessionResponse"];
          };
        };
      };
    };
  };
  "/api/auth/logout": {
    post: {
      responses: {
        /** @description No Content */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/auth/session": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["SessionResponse"];
          };
        };
      };
    };
  };
  "/api/database/credentials/{role}": {
    get: {
      parameters: {
        path: {
          role: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["DatabaseCredentialResponse"];
          };
        };
      };
    };
  };
  "/api/admin/projects": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ProjectResponse"][];
          };
        };
      };
    };
  };
  "/api/admin/projects/{project}": {
    post: {
      parameters: {
        path: {
          project: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateProjectRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ProjectResponse"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          project: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/admin/audit/recent": {
    get: {
      parameters: {
        query?: {
          limit?: number | string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/admin/members": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MemberResponse"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateMemberRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/admin/members/{username}": {
    put: {
      parameters: {
        path: {
          username: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateMemberRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          username: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/admin/members/{username}/roles": {
    post: {
      parameters: {
        path: {
          username: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AssignRolesRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/admin/members/{username}/disable": {
    post: {
      parameters: {
        path: {
          username: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/admin/roles": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["RoleResponse"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateRoleRequest"];
        };
      };
      responses: {
        /** @description No Content */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/admin/roles/{roleName}": {
    delete: {
      parameters: {
        path: {
          roleName: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/admin/machine-identities": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MachineIdentityResponse"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateMachineIdentityRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MachineIdentityResponse"];
          };
        };
      };
    };
  };
  "/api/admin/machine-identities/{roleName}/secret-id": {
    post: {
      parameters: {
        path: {
          roleName: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/admin/machine-identities/{roleName}/secret-id/revoke": {
    post: {
      parameters: {
        path: {
          roleName: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/projects/{project}/environments/{environment}/secrets/list/{folder}": {
    get: {
      parameters: {
        path: {
          project: string;
          environment: string;
          folder: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["SecretEntry"][];
          };
        };
      };
    };
  };
  "/api/projects/{project}/environments/{environment}/secrets/versions/{path}": {
    get: {
      parameters: {
        path: {
          project: string;
          environment: string;
          path: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["SecretVersionResponse"][];
          };
        };
      };
    };
  };
  "/api/projects/{project}/environments/{environment}/secrets/restore/{path}": {
    post: {
      parameters: {
        path: {
          project: string;
          environment: string;
          path: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SecretVersionRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/projects/{project}/environments/{environment}/secrets/undelete/{path}": {
    post: {
      parameters: {
        path: {
          project: string;
          environment: string;
          path: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SecretVersionRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/projects/{project}/environments/{environment}/secrets/export/{path}": {
    get: {
      parameters: {
        query?: {
          format?: string;
        };
        path: {
          project: string;
          environment: string;
          path: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/projects/{project}/environments/{environment}/secrets/import/{path}": {
    post: {
      parameters: {
        path: {
          project: string;
          environment: string;
          path: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ImportSecretsRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/projects/{project}/environments/{environment}/secrets/{path}": {
    get: {
      parameters: {
        path: {
          project: string;
          environment: string;
          path: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["SecretDocumentResponse"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          project: string;
          environment: string;
          path: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SecretDocumentRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          project: string;
          environment: string;
          path: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AssignRolesRequest: {
      roles: string[];
    };
    CreateMachineIdentityRequest: {
      name: string;
      project: string;
      environment: string;
      readOnly: boolean;
      /** Format: int32 */
      tokenTtlSeconds: null | number | string;
      /** Format: int32 */
      tokenUses: null | number | string;
    };
    CreateMemberRequest: {
      username: string;
      password: string;
      policies: string[];
    };
    CreateProjectRequest: {
      description: string;
    };
    CreateRoleRequest: {
      name: string;
      project: string;
      environment: string;
      readOnly: boolean;
    };
    DatabaseCredentialResponse: {
      username: string;
      password: string;
      leaseId: string;
      /** Format: date-time */
      expiresAt: string;
    };
    ImportSecretsRequest: {
      values: {
        [key: string]: string;
      };
      /** Format: int32 */
      expectedVersion: null | number | string;
      description?: null | string;
    };
    LoginRequest: {
      username: string;
      password: string;
    };
    MachineIdentityResponse: {
      name: string;
      roleId: string;
      project: string;
      environment: string;
      readOnly: boolean;
      /** Format: int32 */
      tokenTtlSeconds: null | number | string;
      /** Format: int32 */
      tokenUses: null | number | string;
    };
    MemberResponse: {
      username: string;
      entityId: string;
      disabled: boolean;
      policies: string[];
    };
    ProjectResponse: {
      id: string;
      description: string;
      environments: string[];
    };
    RoleResponse: {
      name: string;
      project: string;
      environment: string;
      readOnly: boolean;
    };
    SecretDocumentRequest: {
      values: {
        [key: string]: string;
      };
      /** Format: int32 */
      expectedVersion: null | number | string;
      description?: null | string;
    };
    SecretDocumentResponse: {
      values: {
        [key: string]: string;
      };
      /** Format: int32 */
      version: number | string;
      description?: null | string;
    };
    SecretEntry: {
      name: string;
      isFolder: boolean;
    };
    SecretVersionRequest: {
      /** Format: int32 */
      version: number | string;
    };
    SecretVersionResponse: {
      /** Format: int32 */
      version: number | string;
      /** Format: date-time */
      deletedAt: null | string;
      destroyed: boolean;
    };
    SessionResponse: {
      /** Format: date-time */
      expiresAt: string;
      policies?: null | string[];
    };
    UpdateMemberRequest: {
      password: string;
      policies: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
